# Generated by Django 5.1.15 on 2026-09-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='cover_letter',
            new_name='description',
        ),
        migrations.AddField(
            model_name='application',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='applications/attachments/'),
        ),
    ]
